name: CI
on:
 workflow_call:
    branches: [ "main" ]
jobs:
  call-global-library:
    uses: dblucas-ops/my-services-simpleone/.github/workflows/mavenCICD.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      personal_access_token: ${{ secrets.token }}
