name: Call Global Library
on:
  workflow_dispatch:  
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)  
  call-global-library:
    uses: dblucas-ops/my-services-simpleone/.github/workflows/mavenCICD.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
