name: Call Global Library
on:
  workflow_dispatch:  
  push:
    branches:
      - main
jobs:
  call-global-library:
    uses: dblucas-ops/my-services-simpleone/.github/workflows/mavenCICD.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
  
