name: Call Global Library 
on:
  workflow_dispatch:  
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Check for properties file
        run: ls -al *.properties
  call-global-library:
    uses: dblucas-ops/my-services-simpleone/.github/workflows/mavenCICD.yml@main
    with:
      config-path: .github/workflows/labeler.yml
    secrets: inherit
