name: Call Node Global Library
on:
  push:
    branches:
      - main
jobs:
  preInit:
    runs-on: ubuntu-latest
    steps:
      - name: Check for properties file
        run: echo "Initialization Section"
  call-global-library:
    uses: dblucas-ops/corporate-node-global-library/.github/workflows/nodeCICD.yml@main
    with:
      callerRepo: call-node-global-library
      branchName: main
      buildCmd: npm install
    secrets: inherit

